// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig, env } from "prisma/config";
import { config } from "dotenv";
import { join } from "path";

// Load .env file explicitly for Prisma config
config({ path: join(process.cwd(), ".env") });

// Use DATABASE_URL for migrations (required by Prisma config)
// The MariaDB adapter in database.ts will use individual variables parsed from DATABASE_URL
const databaseUrl = env("DATABASE_URL");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
    // Disabled shadow database for development (requires CREATE DATABASE permission)
    // shadowDatabaseUrl: shadowDatabaseUrl,
  },
});
